# Generated by Django 4.1.5 on 2023-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/'),
        ),
    ]
