# Generated by Django 3.2.7 on 2023-01-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-date']},
        ),
    ]
