name: StudyBuddy CD

on: 
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: studybud.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ secrets.DEBUG }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

          EMAIL_HOST: ${{ env.EMAIL_HOST }}
          EMAIL_HOST_USER: ${{ env.EMAIL_HOST_USER }}
          EMAIL_PORT: ${{ env.EMAIL_PORT }}
          EMAIL_USE_TLS: ${{ env.EMAIL_USE_TLS }}
          EMAIL_HOST_PASSWORD: ${{ env.EMAIL_HOST_PASSWORD }}

          POSTGRES_ENGINE: ${{ env.POSTGRES_ENGINE }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        run: python3 manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd StudyBuddy
          git pull origin main
          python3 manage.py makemigrations
          python3 manage.py migrate
          sudo systemctl restart nginx

          